### PR TITLE
Support conversion directly from NumPy arrays

### LINKED ISSUE #31: Add a function to accept NumPy arrays and nested iterables
I think it would be nice to use advent_of_code_ocr directly from numpy.

I had set as goal to stay as much as possible with [numpy.ndarrays](https://github.com/pseyfert/advent-of-code-2021/blob/main/13/fold.py#L31) and to use advent_of_code_ocr as it is now, i would need to convert to string, just so that it would internally convert back to numpy.ndarray.

I already broke up the API in my fork https://github.com/pseyfert/advent-of-code-ocr/commits/numpy if you're interested i can open an MR (i made a few unrelated implementation changes which we maybe want to remove from my branch before merging.)

### PR DESCRIPTION
**Pull request by gahjelle**
Fixes #31

### CODE REVIEW

**Comment by gahjelle** [comment]
I added the `annotations` future import to take advantage of some of the newer type annotation features like `|` instead of `typing.Union` while staying compatible with Python 3.7+.

I only added a test using a regular nested list instead of a NumPy array to avoid the complication of adding NumPy as a  dependency. However, I could easily use [`optional-dependencies`](https://flit.readthedocs.io/en/latest/pyproject_toml.html#dependencies) and add a NumPy test as well if you prefer?

**Comment by bsoyka** [comment]
I think it'd be nice to have a NumPy test or two in there, particularly if compatibility with NumPy is going to be in the readme. Let's add it as an optional dependency. :+1:

**Review by bsoyka — APPROVED** [review]
Made a small change to fix tox with the new test dependency, all looks good to me. Thanks again!

**Comment by gahjelle** [comment]
Brilliant! Thanks for supporting this update! 🚀

Do you plan to do an update on PyPI as well? 😊🤞

**Comment by bsoyka** [comment]
Boom! 😉 https://pypi.org/project/advent-of-code-ocr/1.0.0/

**Comment by gahjelle** [comment]
Perfect! Thanks!

**Pull request merged**
